### ISSUE TITLE
Installed via Homebrew?

### ISSUE THREAD

**Issue by sivabudh** [nodenv/nodenv-aliases#10]
Can this plugin be install via Homebrew on macOS / OS X?

**Comment by jasonkarns** [comment]
Yes, via the nodenv tap: https://github.com/nodenv/homebrew-nodenv

We would like to get plugins moved into homebrew core, but they require a minimum number of forks/stars/watchers. So you'd be helping if you starred/forked/watched this repo and any other plugins you use under [nodenv](https://github.com/nodenv)

**Comment by sivabudh** [comment]
@jasonkarns Roger that.
