### ISSUE TITLE
`nodenv alias` isn't doing anything whatsoever

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nodenv/nodenv-aliases#18]
On `nodenv` **1.1.2**, I can't seem to use aliases at all, anymore. (New system, though, so I'm not sure if the version of `nodenv` is what is causing it.)

```
❯ ~ nodenv alias --auto
❯ ~ nodenv alias 9 --auto
Couldn't find any versions for 9
❯ ~ nodenv alias 8 --auto
Couldn't find any versions for 8
❯ ~ nodenv alias 8.9 --auto
Couldn't find any versions for 8.9
❯ ~ ls ~/.nodenv/versions              
total 0
drwxr-xr-x  4 ec  staff   128B 11 Feb 11:13 ./
drwxr-xr-x  5 ec  staff   160B 11 Feb 10:57 ../
drwxr-xr-x  9 ec  staff   288B  9 Feb 06:22 8.9.4/
drwxr-xr-x  9 ec  staff   288B  9 Feb 06:23 9.5.0/
```

The versions are, fairly obviously, there — I'm not sure why `nodenv-alias` isn't seeing them.

**Comment by ELLIOTTCABLE** [comment]
Ahhh, I tracked this down to a problem in another tool (jsahlen/nodenv.plugin.zsh#1), and fixed it. Disregard this. (Although maybe a check-and-warning for the existence of the `versions` folder in whatever directory is set as `$NODENV_ROOT` would be in order … 🤣)

**Comment by jasonkarns** [comment]
You're suggesting throw a warning if `$NODENV_ROOT/versions` doesn't exist?
